import { User } from '@/types/user';
import { RepositoryFile } from '@/types/repositoryFile';

export const MOCK_USERS: User[] = [
  {
    id: 'usr_001',
    fullName: 'System Administrator',
    email: 'admin@example.com',
    username: 'admin',
    password: 'Admin123!',
    role: 'admin',
    department: 'IT',
    permissions: ['IT', 'HR', 'Finance', 'Operations', 'Marketing', 'Legal', 'Administration', 'Procurement', 'Engineering', 'Sales'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'usr_002',
    fullName: 'Sarah Johnson',
    email: 'sarah.johnson@example.com',
    username: 'sarah.johnson',
    password: 'Staff123!',
    role: 'staff',
    department: 'HR',
    permissions: ['HR', 'Administration'],
    isActive: true,
    createdAt: '2024-02-10T09:00:00.000Z',
  },
  {
    id: 'usr_003',
    fullName: 'Michael Chen',
    email: 'michael.chen@example.com',
    username: 'michael.chen',
    password: 'Staff123!',
    role: 'staff',
    department: 'Finance',
    permissions: ['Finance', 'Operations'],
    isActive: true,
    createdAt: '2024-02-15T09:00:00.000Z',
  },
  {
    id: 'usr_004',
    fullName: 'Emily Rodriguez',
    email: 'emily.rodriguez@example.com',
    username: 'emily.rodriguez',
    password: 'Staff123!',
    role: 'staff',
    department: 'Marketing',
    permissions: ['Marketing', 'Sales'],
    isActive: true,
    createdAt: '2024-03-01T09:00:00.000Z',
  },
  {
    id: 'usr_005',
    fullName: 'David Williams',
    email: 'david.williams@example.com',
    username: 'david.williams',
    password: 'Staff123!',
    role: 'staff',
    department: 'IT',
    permissions: ['IT', 'Engineering'],
    isActive: false,
    createdAt: '2024-03-10T09:00:00.000Z',
  },
  {
    id: 'usr_006',
    fullName: 'Lisa Thompson',
    email: 'lisa.thompson@example.com',
    username: 'lisa.thompson',
    password: 'Staff123!',
    role: 'staff',
    department: 'Legal',
    permissions: ['Legal', 'Administration', 'HR'],
    isActive: true,
    createdAt: '2024-03-20T09:00:00.000Z',
  },
];

export const MOCK_FILES: RepositoryFile[] = [
  {
    id: 'file_001',
    title: 'Employee Handbook 2024',
    originalFileName: 'employee_handbook_2024.pdf',
    description: 'Comprehensive employee handbook covering company policies, benefits, code of conduct, and procedures for the year 2024.',
    fileType: 'pdf',
    fileSize: 2457600,
    category: 'HR',
    department: 'HR',
    accessLevel: 'public',
    accessPermissions: ['IT', 'HR', 'Finance', 'Operations', 'Marketing', 'Legal', 'Administration', 'Procurement', 'Engineering', 'Sales'],
    uploadedBy: 'usr_001',
    uploadedByName: 'System Administrator',
    uploadedAt: '2024-01-15T10:00:00.000Z',
    fileUrl: '#mock-file-employee-handbook',
    tags: ['handbook', 'policies', 'onboarding'],
    isActive: true,
  },
  {
    id: 'file_002',
    title: 'Q1 2024 Financial Report',
    originalFileName: 'q1_2024_financial_report.xlsx',
    description: 'Quarterly financial report including P&L statement, balance sheet, cash flow analysis, and budget variance report for Q1 2024.',
    fileType: 'xlsx',
    fileSize: 1843200,
    category: 'Finance',
    department: 'Finance',
    accessLevel: 'department',
    accessPermissions: ['Finance', 'Administration'],
    uploadedBy: 'usr_003',
    uploadedByName: 'Michael Chen',
    uploadedAt: '2024-04-05T14:30:00.000Z',
    fileUrl: '#mock-file-q1-financial',
    tags: ['finance', 'quarterly', 'report'],
    isActive: true,
  },
  {
    id: 'file_003',
    title: 'IT Security Policy',
    originalFileName: 'it_security_policy_v3.docx',
    description: 'Updated IT security policy document covering data protection, password requirements, access control, incident response, and compliance guidelines.',
    fileType: 'docx',
    fileSize: 921600,
    category: 'IT',
    department: 'IT',
    accessLevel: 'public',
    accessPermissions: ['IT', 'HR', 'Finance', 'Operations', 'Marketing', 'Legal', 'Administration', 'Procurement', 'Engineering', 'Sales'],
    uploadedBy: 'usr_001',
    uploadedByName: 'System Administrator',
    uploadedAt: '2024-02-20T11:00:00.000Z',
    fileUrl: '#mock-file-it-security',
    tags: ['security', 'policy', 'IT', 'compliance'],
    isActive: true,
  },
  {
    id: 'file_004',
    title: 'Marketing Campaign Results 2024',
    originalFileName: 'marketing_campaign_results_2024.xlsx',
    description: 'Analysis of all marketing campaigns run in 2024, including conversion rates, ROI, channel performance, and recommendations for improvement.',
    fileType: 'xlsx',
    fileSize: 3145728,
    category: 'Marketing',
    department: 'Marketing',
    accessLevel: 'department',
    accessPermissions: ['Marketing', 'Sales', 'Administration'],
    uploadedBy: 'usr_004',
    uploadedByName: 'Emily Rodriguez',
    uploadedAt: '2024-05-10T09:45:00.000Z',
    fileUrl: '#mock-file-marketing',
    tags: ['marketing', 'campaign', 'analytics'],
    isActive: true,
  },
  {
    id: 'file_005',
    title: 'Staff Directory CSV',
    originalFileName: 'staff_directory_may2024.csv',
    description: 'Complete staff directory with contact information, department assignments, and reporting structure. Updated as of May 2024.',
    fileType: 'csv',
    fileSize: 204800,
    category: 'HR',
    department: 'HR',
    accessLevel: 'public',
    accessPermissions: ['IT', 'HR', 'Finance', 'Operations', 'Marketing', 'Legal', 'Administration', 'Procurement', 'Engineering', 'Sales'],
    uploadedBy: 'usr_002',
    uploadedByName: 'Sarah Johnson',
    uploadedAt: '2024-05-20T08:00:00.000Z',
    fileUrl: '#mock-file-staff-directory',
    tags: ['directory', 'staff', 'contacts'],
    isActive: true,
  },
  {
    id: 'file_006',
    title: 'Legal Contract Templates',
    originalFileName: 'legal_contract_templates.docx',
    description: 'Standard contract templates for vendor agreements, service contracts, NDAs, and employment agreements. Reviewed and approved by legal counsel.',
    fileType: 'docx',
    fileSize: 1638400,
    category: 'Legal',
    department: 'Legal',
    accessLevel: 'restricted',
    accessPermissions: ['Legal', 'Administration'],
    uploadedBy: 'usr_006',
    uploadedByName: 'Lisa Thompson',
    uploadedAt: '2024-03-25T13:00:00.000Z',
    fileUrl: '#mock-file-legal-contracts',
    tags: ['legal', 'contracts', 'templates'],
    isActive: true,
  },
  {
    id: 'file_007',
    title: 'Operations Manual v2.1',
    originalFileName: 'operations_manual_v2.1.pdf',
    description: 'Comprehensive operations manual covering standard operating procedures, workflow documentation, quality control, and process improvement guidelines.',
    fileType: 'pdf',
    fileSize: 5242880,
    category: 'Operations',
    department: 'Operations',
    accessLevel: 'department',
    accessPermissions: ['Operations', 'Engineering', 'Administration'],
    uploadedBy: 'usr_001',
    uploadedByName: 'System Administrator',
    uploadedAt: '2024-04-12T15:20:00.000Z',
    fileUrl: '#mock-file-operations',
    tags: ['operations', 'manual', 'procedures'],
    isActive: true,
  },
  {
    id: 'file_008',
    title: 'Budget Planning Spreadsheet',
    originalFileName: 'budget_planning_2024_2025.xlsx',
    description: 'Annual budget planning spreadsheet for FY2024-2025 including departmental budgets, capital expenditure plans, and forecasting models.',
    fileType: 'xlsx',
    fileSize: 2621440,
    category: 'Finance',
    department: 'Finance',
    accessLevel: 'restricted',
    accessPermissions: ['Finance', 'Administration'],
    uploadedBy: 'usr_003',
    uploadedByName: 'Michael Chen',
    uploadedAt: '2024-06-01T10:30:00.000Z',
    fileUrl: '#mock-file-budget',
    tags: ['budget', 'finance', 'planning', 'FY2025'],
    isActive: true,
  },
  {
    id: 'file_009',
    title: 'Recruitment Process Guide',
    originalFileName: 'recruitment_process_guide.pdf',
    description: 'Step-by-step guide for the recruitment and onboarding process, including job posting templates, interview guidelines, and orientation checklist.',
    fileType: 'pdf',
    fileSize: 1310720,
    category: 'HR',
    department: 'HR',
    accessLevel: 'department',
    accessPermissions: ['HR', 'Administration'],
    uploadedBy: 'usr_002',
    uploadedByName: 'Sarah Johnson',
    uploadedAt: '2024-04-30T11:15:00.000Z',
    fileUrl: '#mock-file-recruitment',
    tags: ['recruitment', 'HR', 'hiring', 'onboarding'],
    isActive: true,
  },
  {
    id: 'file_010',
    title: 'Network Infrastructure Diagram',
    originalFileName: 'network_infrastructure_2024.pdf',
    description: 'Technical diagram showing the complete network infrastructure including server topology, security zones, VPN configurations, and disaster recovery setup.',
    fileType: 'pdf',
    fileSize: 4194304,
    category: 'IT',
    department: 'IT',
    accessLevel: 'restricted',
    accessPermissions: ['IT', 'Engineering'],
    uploadedBy: 'usr_001',
    uploadedByName: 'System Administrator',
    uploadedAt: '2024-05-08T14:00:00.000Z',
    fileUrl: '#mock-file-network',
    tags: ['network', 'infrastructure', 'IT', 'technical'],
    isActive: true,
  },
  {
    id: 'file_011',
    title: 'Sales Performance Data Q2',
    originalFileName: 'sales_performance_q2_2024.csv',
    description: 'Sales performance data for Q2 2024 including individual sales rep performance, regional breakdowns, product line analysis, and target vs actual comparison.',
    fileType: 'csv',
    fileSize: 512000,
    category: 'Sales',
    department: 'Sales',
    accessLevel: 'department',
    accessPermissions: ['Sales', 'Marketing', 'Administration'],
    uploadedBy: 'usr_004',
    uploadedByName: 'Emily Rodriguez',
    uploadedAt: '2024-07-05T09:00:00.000Z',
    fileUrl: '#mock-file-sales',
    tags: ['sales', 'performance', 'quarterly', 'Q2'],
    isActive: true,
  },
  {
    id: 'file_012',
    title: 'Procurement Policy Document',
    originalFileName: 'procurement_policy_2024.docx',
    description: 'Updated procurement policy covering vendor selection criteria, approval workflows, purchase order procedures, and supplier relationship management.',
    fileType: 'docx',
    fileSize: 737280,
    category: 'Procurement',
    department: 'Procurement',
    accessLevel: 'public',
    accessPermissions: ['IT', 'HR', 'Finance', 'Operations', 'Marketing', 'Legal', 'Administration', 'Procurement', 'Engineering', 'Sales'],
    uploadedBy: 'usr_001',
    uploadedByName: 'System Administrator',
    uploadedAt: '2024-03-15T08:30:00.000Z',
    fileUrl: '#mock-file-procurement',
    tags: ['procurement', 'policy', 'vendors'],
    isActive: true,
  },
  {
    id: 'file_013',
    title: 'Google Analytics Dashboard',
    originalFileName: 'analytics_dashboard_link.sheet',
    description: 'Live Google Sheets dashboard connected to analytics data for real-time marketing performance monitoring.',
    fileType: 'sheet',
    fileSize: 0,
    category: 'Marketing',
    department: 'Marketing',
    accessLevel: 'department',
    accessPermissions: ['Marketing', 'Sales', 'Administration'],
    uploadedBy: 'usr_004',
    uploadedByName: 'Emily Rodriguez',
    uploadedAt: '2024-06-15T10:00:00.000Z',
    fileUrl: '#mock-sheet-analytics',
    spreadsheetLink: 'https://docs.google.com/spreadsheets/d/example',
    tags: ['analytics', 'marketing', 'dashboard', 'google-sheets'],
    isActive: true,
  },
  {
    id: 'file_014',
    title: 'Engineering Standards Guide',
    originalFileName: 'engineering_standards_v1.pdf',
    description: 'Technical standards and best practices guide for the engineering team covering code standards, architecture patterns, review processes, and documentation requirements.',
    fileType: 'pdf',
    fileSize: 3670016,
    category: 'Engineering',
    department: 'Engineering',
    accessLevel: 'department',
    accessPermissions: ['Engineering', 'IT'],
    uploadedBy: 'usr_005',
    uploadedByName: 'David Williams',
    uploadedAt: '2024-05-25T13:30:00.000Z',
    fileUrl: '#mock-file-engineering',
    tags: ['engineering', 'standards', 'technical', 'development'],
    isActive: true,
  },
  {
    id: 'file_015',
    title: 'Annual Leave Policy',
    originalFileName: 'annual_leave_policy_2024.pdf',
    description: 'Updated annual leave policy covering entitlements, application procedures, carry-over rules, public holidays, and special leave provisions.',
    fileType: 'pdf',
    fileSize: 614400,
    category: 'HR',
    department: 'HR',
    accessLevel: 'public',
    accessPermissions: ['IT', 'HR', 'Finance', 'Operations', 'Marketing', 'Legal', 'Administration', 'Procurement', 'Engineering', 'Sales'],
    uploadedBy: 'usr_002',
    uploadedByName: 'Sarah Johnson',
    uploadedAt: '2024-01-20T09:00:00.000Z',
    fileUrl: '#mock-file-leave-policy',
    tags: ['HR', 'leave', 'policy', 'benefits'],
    isActive: true,
  },
];
